apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service.name" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.service.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        {{- include "service.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "service.name" . }}
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health
              port: 8080
              scheme: HTTP
  strategy:
    canary:
      dynamicStableScale: true
      analysis:
        templates:
        - templateName: {{ include "service.name" . }}-analysis-template
      trafficRouting:
        istio:
          virtualService:
            routes:
            - primary
            name: {{ include "service.name" . }}
          destinationRule:
            name: {{ include "service.name" . }}
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: 10
        - pause:
            duration: 1h # 1 hour
        - setWeight: 20
        - pause: {} # pause indefinitely