apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: film-storage-blue-green
  namespace: user15-gitops-argocd
spec:
  destination:
    namespace: user15-blue-green
    server: 'https://kubernetes.default.svc'
  source:
    path: blue-green
    repoURL: https://github.com/next-rubenfernandez/workshop-argo-rollouts-resources
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true